apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - mongodb-data.pv.yaml
  - mongodb-data.pvc.yaml
  - mongodb.pod.yaml
  - mongodb.svc.yaml
configMapGenerator:
  - name: mongodb-envs
    literals:
      - MONGO_INITDB_ROOT_USERNAME=root
  - name: config-envs
    literals:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
    behavior: merge
secretGenerator:
  - name: mongodb-envs
    literals:
      - MONGO_INITDB_ROOT_PASSWORD=Secret123
  - name: config-envs
    literals:
      - MONGODB_PASSWORD=Secret123
    behavior: merge
configurations:
  - configurations.yaml
