apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  labels:
    app.kubernetes.io/component: mongodb
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
