apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data
  labels:
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: hostpath
  hostPath:
    path: /data/mongodb-data
