apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: mongodb
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: mongodb
