apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5
          envFrom:
            - configMapRef:
                name: mongodb-envs
            - secretRef:
                name: mongodb-envs
          volumeMounts:
            - name: data
              mountPath: /data/db
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongodb-data
