apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    useDockerCLI: true
    useBuildkit: false
    push: false
    tryImportMissing: false
  artifacts:
    - image: goapp
      docker:
        dockerfile: build/goapp/Dockerfile
  tagPolicy:
    gitCommit: {}
test:
  - image: goapp
    structureTests:
      - test/goapp/container-structure.yaml
profiles:
  - name: dev
    activation:
      - command: dev
      - command: debug
    deploy:
      kubeContext: docker-desktop
      kustomize:
        paths:
          - deploy/goapp/overlays/dev
  - name: prod
    deploy:
      kubeContext: docker-desktop
      kustomize:
        paths:
          - deploy/goapp/overlays/prod
