apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: goapp
      docker:
        dockerfile: build/goapp/Dockerfile
  tagPolicy:
    gitCommit: {}
test:
  - image: goapp
    structureTests:
      - test/goapp/container-structure.yaml
profiles:
  - name: dev
    activation:
      - command: dev
      - command: debug
    build:
      local:
        useDockerCLI: true
        push: false
        tryImportMissing: false
    deploy:
      kubeContext: docker-desktop
      helm:
        releases:
          - name: goapp-dev
            namespace: default
            chartPath: deploy/goapp
            valuesFiles:
              - deploy/goapp/releases/goapp-dev/values.yaml
            artifactOverrides:
              image: goapp
            imageStrategy:
              helm: {}
  - name: prod
    build:
      googleCloudBuild:
        projectId: gomod-0
    deploy:
      kubeContext: gke_gomod-0_europe-central2_autopilot-cluster-1
      helm:
        releases:
          - name: goapp-prod
            namespace: default
            chartPath: deploy/goapp
            valuesFiles:
              - deploy/goapp/releases/goapp-prod/values.yaml
              - deploy/goapp/releases/goapp-prod/secrets.dec.yaml
            artifactOverrides:
              image: goapp
            imageStrategy:
              helm: {}
        hooks:
          before:
            - host:
                command:
                  - sh
                  - -c
                  - sops --decrypt --output=deploy/goapp/releases/goapp-prod/secrets.dec.yaml deploy/goapp/releases/goapp-prod/secrets.enc.yaml
          after:
            - host:
                command:
                  - sh
                  - -c
                  - rm -f deploy/goapp/releases/goapp-prod/secrets.dec.yaml
