apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    useDockerCLI: true
    useBuildkit: false
    push: false
    tryImportMissing: false
  artifacts:
    - image: ghcr.io/damlys/gomod-goapp
      docker:
        dockerfile: build/goapp/Dockerfile
        target: rte
  tagPolicy:
    gitCommit: {}
test:
  - image: ghcr.io/damlys/gomod-goapp
    structureTests:
      - build/goapp/container-structure-test.yaml
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kubeContext: docker-desktop
      kustomize:
        paths:
          - deployments/goapp/overlays/dev
  - name: debug
    activation:
      - command: debug
    deploy:
      kubeContext: docker-desktop
      kustomize:
        paths:
          - deployments/goapp/overlays/dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: sdk
  - name: prod
    deploy:
      kubeContext: docker-desktop
      kustomize:
        paths:
          - deployments/goapp/overlays/prod
