apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: goapp
      docker:
        dockerfile: build/goapp/Dockerfile
  tagPolicy:
    gitCommit: {}
test:
  - image: goapp
    structureTests:
      - test/goapp/container-structure.yaml
profiles:
  - name: dev
    activation:
      - command: dev
      - command: debug
    build:
      local:
        useDockerCLI: true
        useBuildkit: false
        push: false
        tryImportMissing: false
    deploy:
      kubeContext: docker-desktop
      kustomize:
        paths:
          - deploy/goapp/overlays/dev
  - name: prod
    deploy:
      kubeContext: gke_gomod-0_europe-central2_autopilot-cluster-1
      kustomize:
        paths:
          - deploy/goapp/overlays/prod
        hooks:
          before:
            - host: { command: ["scripts/sops/decrypt.sh"] }
          after:
            - host: { command: ["scripts/sops/rm-decrypted.sh"] }
