apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    useDockerCLI: true
    useBuildkit: false
    push: false
    tryImportMissing: false
  artifacts:
    - image: goapp
      docker:
        dockerfile: build/goapp/Dockerfile
  tagPolicy:
    gitCommit: {}
test:
  - image: goapp
    structureTests:
      - test/goapp/container-structure.yaml
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kubeContext: docker-desktop
      kustomize:
        paths:
          - deploy/goapp/overlays/dev
  - name: debug
    activation:
      - command: debug
    patches:
      - op: add
        path: /build/artifacts/0/docker/target
        value: sdk
      - op: remove
        path: /test/0
    deploy:
      kubeContext: docker-desktop
      kustomize:
        paths:
          - deploy/goapp/overlays/dev
  - name: prod
    deploy:
      kubeContext: docker-desktop
      kustomize:
        paths:
          - deploy/goapp/overlays/prod
