apiVersion: skaffold/v4beta13
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: europe-central2-docker.pkg.dev/gogcp-main-8/private-docker-images/gomod/goapp
      context: .
      docker:
        dockerfile: build/goapp/Dockerfile
test:
  - image: europe-central2-docker.pkg.dev/gogcp-main-8/private-docker-images/gomod/goapp
    structureTests:
      - test/goapp/container-structure-test.yaml

profiles:
  - name: dev
    activation:
      - command: dev
      - command: debug
    build:
      local:
        useDockerCLI: true
        push: false
    deploy:
      helm:
        releases:
          - remoteChart: oci://europe-central2-docker.pkg.dev/gogcp-main-8/private-helm-charts/gorun/apps/http-server
            version: 0.8.100
            name: goapp-dev
            namespace: default
            valuesFiles:
              - deploy/helm-releases/goapp-dev/values.yaml
      kubeContext: docker-desktop
    portForward:
      - resourceType: service
        resourceName: goapp-dev
        namespace: default
        port: 8080
        localPort: 8080

  - name: test
    build:
      local:
        useDockerCLI: true
        push: true
    deploy:
      helm:
        releases:
          - remoteChart: oci://europe-central2-docker.pkg.dev/gogcp-main-8/private-helm-charts/gorun/apps/http-server
            version: 0.8.100
            name: goapp-test-8
            namespace: gomod-test-8
            valuesFiles:
              - deploy/helm-releases/goapp-test-8/values.yaml
      kubeContext: gke_gogcp-test-8_europe-central2-a_gogke-test-8
