apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - http-server.deploy.yaml
  - http-server.svc.yaml
configMapGenerator:
  - name: config-envs
  - name: config-files
secretGenerator:
  - name: config-envs
  - name: config-files
images:
  - name: goapp
    newName: ghcr.io/damlys/gomod-goapp
