apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - http-server.hpa.yaml
configMapGenerator:
  - name: config-envs
    envs:
      - config-files/config.env
    behavior: merge
  - name: config-files
    files:
      - config-files/config.json
      - config-files/config.txt
      - config-files/config.yaml
    behavior: merge
secretGenerator:
  - name: config-envs
    envs:
      - config-files/secret.dec.env
    behavior: merge
  - name: config-files
    files:
      - config-files/secret.dec.json
      - config-files/secret.dec.txt
      - config-files/secret.dec.yaml
    behavior: merge
namespace: default
namePrefix: goapp-
nameSuffix: -prod
commonLabels:
  app.kubernetes.io/part-of: gomod
  app.kubernetes.io/name: goapp
  app.kubernetes.io/instance: prod
