apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - http-server.hpa.yaml
  - http-server.ing.yaml
configMapGenerator:
  - name: config-envs
    envs:
      - config.env
    behavior: merge
  - name: config-files
    files:
      - config.json
      - config.txt
    behavior: merge
secretGenerator:
  - name: config-envs
    envs:
      - secret.dec.env
    behavior: merge
  - name: config-files
    files:
      - secret.dec.json
      - secret.dec.txt
    behavior: merge
namespace: default
namePrefix: goapp-
nameSuffix: -prod
commonLabels:
  app.kubernetes.io/part-of: gomod
  app.kubernetes.io/name: goapp
  app.kubernetes.io/instance: prod
