apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "goapp.metadataLabels" $ | nindent 4 }}
data:
  {{- range $key, $val := .Values.envs.configMap }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
