apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "goapp.metadataLabels" $ | nindent 4 }}
data:
  {{- range $key, $val := .Values.envs.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
