apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "goapp.metadataLabels" $ | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "goapp.matchLabels" $ | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
