apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  labels:
    app.kubernetes.io/component: http-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: http-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: http-server
      annotations:
        prometheus.io/scrape: "false"
        prometheus.io/port: http
        prometheus.io/path: /-/metrics
    spec:
      containers:
        - name: http-server
          image: goapp
          envFrom:
            - configMapRef:
                name: config-envs
            - secretRef:
                name: config-envs
          volumeMounts:
            - name: config-files
              mountPath: /run/secrets/goapp
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http
              path: /-/ready
          livenessProbe:
            httpGet:
              port: http
              path: /-/healthy
          resources:
            requests:
              memory: 128M
            limits:
              cpu: 1000m
              memory: 256M
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - CAP_CHOWN
      volumes:
        - name: config-files
          projected:
            sources:
              - configMap:
                  name: config-files
              - secret:
                  name: config-files
