#!/bin/bash
set -e

function main {
  skaffold build --profile="dev" --file-output="./skaffold-build-artifacts.json"
  skaffold test --profile="dev" --build-artifacts="./skaffold-build-artifacts.json"
}

main "$@"
