#!/usr/bin/env bash
set -e

go fmt ./...
go vet ./...
golangci-lint run ./...
go test -v ./...

skaffold build --profile=dev --file-output=skaffold-build-artifacts.json
skaffold test --profile=dev --build-artifacts=skaffold-build-artifacts.json
skaffold render --profile=dev --output=skaffold-render-manifests.yaml --digest-source=tag
