apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-http-server"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: http-server
    {{- include "goapp.metadataLabels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.httpServer.minReplicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: http-server
      {{- include "goapp.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: http-server
        {{- include "goapp.metadataLabels" $ | nindent 8 }}
      annotations:
        prometheus.io/scrape: "false"
        prometheus.io/port: http
        prometheus.io/path: /-/metrics
        checksum/configs: "{{ include "goapp.configsChecksum" $ }}"
    spec:
      containers:
        - name: http-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-config-envs"
            - secretRef:
                name: "{{ .Release.Name }}-config-envs"
          volumeMounts:
            - name: config-files
              mountPath: /run/secrets/goapp
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http
              path: /-/ready
          livenessProbe:
            httpGet:
              port: http
              path: /-/healthy
          resources:
            requests:
              memory: 128M
            limits:
              cpu: 1000m
              memory: 256M
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - CAP_CHOWN
      volumes:
        - name: config-files
          projected:
            sources:
              - configMap:
                  name: "{{ .Release.Name }}-config-files"
              - secret:
                  name: "{{ .Release.Name }}-config-files"
