name: workflow0
on:
  pull_request:
    paths:
      - "**"
      - "!**.md"
  push:
    paths:
      - "**"
      - "!**.md"
    branches:
      - main
jobs:
  job0:
    name: job0
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gorun-devcontainer:0.8.100
    steps:
      - name: git clone (PR)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: git clone (not PR)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
      - name: git clone (fix)
        run: git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: git config user
        run: git config --global user.name "github-actions" && git config --global user.email "github-actions@github.com"

      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: docker auth (Google Artifact Registry)
        run: gcloud auth configure-docker "europe-central2-docker.pkg.dev"
      - name: helm auth (Google Artifact Registry)
        run: gcloud auth print-access-token | helm registry login --username="oauth2accesstoken" --password-stdin "europe-central2-docker.pkg.dev"
      - name: kube auth (Google Kubernetes Engine)
        run: gcloud --project="gogcp-test-8" container clusters --region="europe-central2-a" get-credentials "gogke-test-8"
      - name: kube namespace
        run: kubectl config set-context --current --namespace="gomod-test-8"

      - name: download dependencies
        run: ./scripts/go-download-dependencies
      - name: scan vulnerabilities
        run: ./scripts/go-scan-vulnerabilities
        continue-on-error: true
      - name: format check
        run: ./scripts/go-format-check
      - name: lint
        run: ./scripts/go-lint
      - name: build
        run: ./scripts/go-build
      - name: test
        run: ./scripts/go-test

      - name: test images
        run: ./scripts/skaffold-test

      - name: deploy to test env
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: skaffold run --profile="test"
