name: workflow0
on:
  push:
    branches:
      - develop
      - main
      - "releases/**"
    tags:
      - "v**"
    paths:
      - "**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!**.md"
jobs:
  job0:
    runs-on: ubuntu-22.04
    steps:
      - name: Set Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Clone Git repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Install Skaffold
        run: brew install skaffold
      - name: Install Container Structure Tests
        run: brew install container-structure-test

      - name: Format Go code
        run: go fmt ./...
      - name: Lint Go code
        run: go vet ./...
      - name: Test Go code
        run: go test -v ./...

      - name: Build Docker containers
        run: skaffold build --file-output=skaffold-build-artifacts.json
      - name: Test Docker containers
        run: skaffold test --build-artifacts=skaffold-build-artifacts.json

      - if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        name: Deploy to non-prod
        env:
          SKAFFOLD_DIGEST_SOURCE: tag
        run: skaffold render --profile=dev
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Deploy to prod
        env:
          SKAFFOLD_DIGEST_SOURCE: tag
        run: skaffold render --profile=prod
