name: workflow0
on:
  push:
    branches:
      - develop
      - main
      - "releases/**"
    tags:
      - "v**"
    paths:
      - "**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!**.md"
jobs:
  job0:
    permissions:
      id-token: "write"
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/damlys/godev:2022-09-04-16-05-13-8d7f6d8
      options: --user=root
    steps:
      - name: Set Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Clone Git repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/141074763701/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "github-actions@gomod-0.iam.gserviceaccount.com"
      - name: Authenticate to Docker registry
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev
      - name: Authenticate to Kubernetes cluster
        run: gcloud container clusters get-credentials autopilot-cluster-1 --region europe-central2 --project gomod-0

      - name: Format Go code
        run: go fmt ./...
      - name: Vet Go code
        run: go vet ./...
      - name: Lint Go code
        run: golangci-lint run ./...
      - name: Download Go dependencies
        run: go mod download
      - name: Test Go code
        run: go test -v ./...

      - name: Build Docker images
        if: github.event_name == 'pull_request'
        run: skaffold build --profile=dev --file-output=skaffold-build-artifacts.json
      - name: Test Docker images
        if: github.event_name == 'pull_request'
        run: skaffold test --profile=dev --build-artifacts=skaffold-build-artifacts.json
      - name: Lint Helm charts
        if: github.event_name == 'pull_request'
        run: helm lint ./deploy/*

      - name: Deploy to prod
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: skaffold run --profile=prod --default-repo="europe-central2-docker.pkg.dev/gomod-0/gomod"
