image:
  repository: goapp
  tag: latest

configEnvs: {}
secretEnvs: {}
configFiles: {}
secretFiles: {}

httpServer:
  minReplicas: 1
  maxReplicas: 1

  prometheus:
    scrape: false

  ingress:
    annotations: {}
    host: ""
    path: /
